import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className="bg-gray-50 text-gray-900 min-h-screen">
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-64 bg-white border-r shadow-sm flex flex-col">
            <div className="h-20 flex items-center justify-center border-b">
              <span className="font-bold text-xl tracking-tight">ShopSense</span>
            </div>
            <nav className="flex-1 px-4 py-6 space-y-2">
              <a href="/dashboard" className="block px-3 py-2 rounded hover:bg-gray-100 font-medium">Dashboard</a>
              <a href="/products" className="block px-3 py-2 rounded hover:bg-gray-100 font-medium">Produtos</a>
              <a href="/categories" className="block px-3 py-2 rounded hover:bg-gray-100 font-medium">Categorias</a>
            </nav>
            <div className="p-4 border-t">
              <button className="w-full px-3 py-2 rounded bg-gray-100 hover:bg-gray-200 text-sm font-medium">Logout</button>
            </div>
          </aside>
          {/* Main content */}
          <main className="flex-1 flex flex-col">
            {/* Header */}
            <header className="h-20 px-8 flex items-center border-b bg-white">
              <h1 className="text-2xl font-semibold">Sistema de Gestão de Produtos</h1>
              <div className="ml-auto flex items-center gap-4">
                {/* Usuário logado (mock) */}
                <span className="text-sm text-gray-600">Olá, Usuário</span>
                <img src="/avatar.png" alt="Avatar" className="w-8 h-8 rounded-full border" />
              </div>
            </header>
            <section className="flex-1 p-8">
              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}