services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - hypesoft-network
    restart: unless-stopped
    # Não precisa de volumes nem variáveis de root, pois usará Atlas

  postgres-keycloak:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    networks:
      - hypesoft-network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: keycloak
    command: start-dev
    ports:
        - "8080:8080"
    networks:
      - hypesoft-network
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres-keycloak
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:8080"
    networks:
      - hypesoft-network
    env_file:
      - ./backend/.env
    depends_on:
      keycloak:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - hypesoft-network
    env_file:
      - ./frontend/.env.local
    depends_on:
      backend:
        condition: service_started
      keycloak:
        condition: service_started
    restart: unless-stopped

networks:
  hypesoft-network:
    driver: bridge